#!/usr/bin/env python3
"""Fill the metadata that only a human can obtain (archive DOI, ORCID iDs).

    python tools/set_metadata.py --doi 10.5281/zenodo.1234567
    python tools/set_metadata.py --orcid-liu 0009-... --orcid-chen 0009-...

Every flag is optional and the script is idempotent: run it again with a
corrected value and it overwrites the previous one. It edits paper/main.tex
(Data availability, title page) and README.md so the two never disagree.

After it runs, rebuild and re-verify:

    python tools/verify_paper_numbers.py
    cd paper && pdflatex -interaction=nonstopmode main && bibtex main \
        && pdflatex -interaction=nonstopmode main && pdflatex -interaction=nonstopmode main
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/oscarliu2019/plugin-selection-audit"
ANCHOR = "\\bibliographystyle{elsarticle-num}"
DOI_BEGIN = "% >>> archive DOI (generated by tools/set_metadata.py)"
DOI_END = "% <<< archive DOI"
SWH_BEGIN = "% >>> Software Heritage archive (generated by tools/set_metadata.py)"
SWH_END = "% <<< Software Heritage archive"


README_BEGIN = "<!-- metadata: generated by tools/set_metadata.py -->"
README_END = "<!-- /metadata -->"


def _strip_block(text: str, begin: str, end: str) -> str:
    return re.sub(
        re.escape(begin) + r".*?" + re.escape(end) + r"\n", "", text, flags=re.S
    )


def _strip_legacy(text: str) -> str:
    """Remove the hand-written archive paragraphs this script now owns.

    The first SWHID and DOI sentences were added by hand before the script
    existed; without this the marked block would duplicate them. Only text
    outside the generated blocks is touched, otherwise setting the DOI would
    eat the body of the Software Heritage block and leave a dangling marker.
    """
    blocks = re.compile(
        "("
        + re.escape(DOI_BEGIN)
        + r".*?"
        + re.escape(DOI_END)
        + "|"
        + re.escape(SWH_BEGIN)
        + r".*?"
        + re.escape(SWH_END)
        + ")",
        re.S,
    )
    legacy = (
        r"\nThe repository is also archived permanently in Software Heritage:.*?\n\n",
        r"\nThe exact release from which every number in this manuscript was"
        r" computed is.*?\n\n",
    )
    out = []
    for i, part in enumerate(blocks.split(text)):
        if i % 2 == 0:  # outside any generated block
            for pat in legacy:
                part = re.sub(pat, "\n", part, flags=re.S)
        out.append(part)
    return "".join(out)


def _readme_set(**lines: str | None) -> None:
    """Keep the README metadata lines in one marked block under the title."""
    rd = ROOT / "README.md"
    if not rd.exists():
        return
    text = rd.read_text()
    keys = ("doi", "swhid")
    current: dict[str, str] = {}
    m = re.search(
        re.escape(README_BEGIN) + r"\n(.*?)" + re.escape(README_END), text, flags=re.S
    )
    if m:
        for line in (l for l in m.group(1).split("\n") if l.strip()):
            if line.startswith("DOI:"):
                current["doi"] = line
            elif line.startswith("Archived in Software Heritage"):
                current["swhid"] = line
        text = _strip_block(text, README_BEGIN, README_END)
    # drop the pre-script hand-written lines wherever they sit
    text = re.sub(r"^DOI: .*\n\n?", "", text, flags=re.M)
    text = re.sub(r"^Archived in Software Heritage: .*\n\n?", "", text, flags=re.M)
    current.update({k: v for k, v in lines.items() if v})
    body = "\n\n".join(current[k] for k in keys if k in current)
    block = f"{README_BEGIN}\n{body}\n{README_END}\n"

    out = text.split("\n")
    at = 1 if out and out[0].startswith("# ") else 0
    while at < len(out) and not out[at].strip():
        at += 1
    out.insert(at, block)
    rd.write_text(re.sub(r"\n{3,}", "\n\n", "\n".join(out)))


def set_doi(doi: str) -> None:
    doi = doi.strip().removeprefix("https://doi.org/").removeprefix("doi:")
    url = f"https://doi.org/{doi}"

    tex = ROOT / "paper/main.tex"
    s = _strip_legacy(_strip_block(tex.read_text(), DOI_BEGIN, DOI_END))
    block = (
        f"{DOI_BEGIN}\n"
        "The exact release from which every number in this manuscript was computed is\n"
        f"archived, with all artifacts, at \\url{{{url}}} (DOI: \\texttt{{{doi}}}); the\n"
        "repository above is its development mirror.\n"
        f"{DOI_END}\n\n"
    )
    if ANCHOR not in s:
        raise SystemExit(f"anchor {ANCHOR!r} not found in paper/main.tex")
    tex.write_text(s.replace(ANCHOR, block + ANCHOR, 1))
    _readme_set(doi=f"DOI: [{doi}]({url})")
    print(f"[doi] {doi}")


def set_swhid(rev: str, snp: str | None = None) -> None:
    rev = rev.strip()
    if not re.fullmatch(r"swh:1:rev:[0-9a-f]{40}", rev):
        raise SystemExit(f"not a Software Heritage revision id: {rev}")
    visit = f", visit \\texttt{{{snp}}}" if snp else ""
    tex = ROOT / "paper/main.tex"
    s = _strip_legacy(_strip_block(tex.read_text(), SWH_BEGIN, SWH_END))
    block = (
        f"{SWH_BEGIN}\n"
        "The repository is also archived permanently in Software Heritage: the revision\n"
        f"from which this manuscript was produced is\n\\texttt{{{rev}}} (origin\n"
        f"\\url{{{REPO_URL}}}{visit}).\n"
        f"{SWH_END}\n\n"
    )
    tex.write_text(s.replace(ANCHOR, block + ANCHOR, 1))
    _readme_set(
        swhid="Archived in Software Heritage: `"
        + rev
        + "`"
        + (f" (visit `{snp}`)." if snp else ".")
    )
    print(f"[swhid] {rev}")


def set_orcid(liu: str | None, chen: str | None) -> None:
    tex = ROOT / "paper/main.tex"
    s = tex.read_text()
    for name, orcid in (("Mianhan Liu", liu), ("Chen Chen", chen)):
        if not orcid:
            continue
        orcid = orcid.strip().removeprefix("https://orcid.org/")
        if not re.fullmatch(r"\d{4}-\d{4}-\d{4}-\d{3}[\dX]", orcid):
            raise SystemExit(f"not an ORCID iD: {orcid}")
        pat = re.compile(r"\\author\[1\]\{" + re.escape(name) + r"\}(\[orcid=[^\]]*\])?")
        s, k = pat.subn("\\\\author[1]{" + name + "}[orcid=" + orcid + "]", s, count=1)
        if not k:
            raise SystemExit(f"author block for {name} not found")
        print(f"[orcid] {name}: {orcid}")
    if "[orcid=" in s:
        # cas-sc suppresses the title-page footnote only while no iD is registered
        s = s.replace("\\AtBeginDocument{\\renewcommand{\\printorcid}{}}\n", "")
    tex.write_text(s)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--doi")
    ap.add_argument("--orcid-liu")
    ap.add_argument("--orcid-chen")
    ap.add_argument("--swhid", help="swh:1:rev:<40 hex>")
    ap.add_argument("--swh-snapshot", help="swh:1:snp:<40 hex>")
    a = ap.parse_args()
    if not any((a.doi, a.orcid_liu, a.orcid_chen, a.swhid)):
        ap.error("nothing to do: pass --doi, --swhid and/or --orcid-*")
    if a.doi:
        set_doi(a.doi)
    if a.swhid:
        set_swhid(a.swhid, a.swh_snapshot)
    set_orcid(a.orcid_liu, a.orcid_chen)
    print("now rebuild: see the docstring of this file")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
